services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - postgres
    volumes:
      - ../backend:/app
      - ../backend/logs:/var/log/gunicorn
      - ../backend/logs:/var/log/cron

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    

volumes:
  postgres-data: