# Generated by Django 5.1.2 on 2024-11-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendships',
            old_name='user1_id',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='friendships',
            old_name='user2_id',
            new_name='user2',
        ),
        migrations.AlterField(
            model_name='friendships',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
