# Generated by Django 5.1.2 on 2024-11-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_rename_user1_id_friendships_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
