# Generated by Django 5.1.2 on 2024-11-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0004_alter_friendships_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
