# Generated by Django 5.1.2 on 2024-11-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_messages_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='IsVisibleToReceiver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='IsVisibleToSender',
            field=models.BooleanField(default=True),
        ),
    ]
