# Generated by Django 5.1.2 on 2024-11-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
