# Generated by Django 5.1.2 on 2024-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='IsOAuth',
            field=models.BooleanField(default=False),
        ),
    ]
